name: Docs
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    publish-site:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            
            - name: Install
              run: npm ci
            - name: Build Docs
              run: npm run build:docs
            
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: docs
                  folder: docs
                  git-config-name: BonkersSDK Bot